-- Финальный открытый пакет документов VEDAL от 11 сентября 2026.
--
-- Источник: папка RAG_VEDAL_MED, переданная для открытого размещения и
-- индексации Ведалиной. Всё, чего в этом пакете нет, убирается из админки и
-- публичного перечня, чтобы сайт не обещал регистрационные удостоверения,
-- лицензии или декларации, которых заказчик не передал для публикации.

alter table document drop constraint document_doc_group_check;

delete from deal_document
where document_id in (
    select id
    from document
    where slug not in (
        'vedal-product-catalog',
        'vedal-buklet-innoprom-2026',
        'vedal-utpp-membership-ticket',
        'vedal-certificate-conformity',
        'vedal-a-2000-product-sheet',
        'vedal-r1-product-sheet',
        'vedal-r2-product-sheet',
        'vedal-t-100-product-sheet'
    )
);

delete from document
where slug not in (
    'vedal-product-catalog',
    'vedal-buklet-innoprom-2026',
    'vedal-utpp-membership-ticket',
    'vedal-certificate-conformity',
    'vedal-a-2000-product-sheet',
    'vedal-r1-product-sheet',
    'vedal-r2-product-sheet',
    'vedal-t-100-product-sheet'
);

alter table document add constraint document_doc_group_check
    check (doc_group in ('Техническая документация',
                         'Система качества',
                         'Коммерческие материалы',
                         'О компании'));

insert into document (id, slug, title, doc_group, subject, product_slug,
                      sensitivity, access, listed, published, language,
                      storage_key, file_size, revision, source_owner, approved_by,
                      created_at, updated_at)
values
    ('41094c28-4e81-4ec0-8b6d-6bb0d21f4551',
     'vedal-product-catalog',
     'Каталог продукции VEDAL',
     'Коммерческие материалы',
     'Все изделия',
     null,
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-product-catalog.pdf',
     2055913,
     'актуальная редакция',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now()),
    ('0f6a4ed3-f3fb-459d-aad0-0a7379b520fd',
     'vedal-buklet-innoprom-2026',
     'Буклет VEDAL для ИННОПРОМ',
     'Коммерческие материалы',
     'Все изделия',
     null,
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-buklet-innoprom-2026.pdf',
     2803411,
     'ИННОПРОМ 2026',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now()),
    ('fdb05206-0e73-49d1-8abf-a99d360244aa',
     'vedal-utpp-membership-ticket',
     'Членский билет Уральской торгово-промышленной палаты',
     'О компании',
     'ООО «ВЕДАЛ»',
     null,
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-utpp-membership-ticket.pdf',
     321856,
     'MB-SVE-12936',
     'Уральская торгово-промышленная палата (Союз)',
     'system:migration',
     now(),
     now()),
    ('e6f67f2a-552d-40c5-93bb-a040e1f1df48',
     'vedal-certificate-conformity',
     'Сертификат соответствия ООО «ВЕДАЛ»',
     'Система качества',
     'ООО «ВЕДАЛ»',
     null,
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-certificate-conformity.pdf',
     509180,
     'РОСС RU.НА83.СМК00331',
     'ОС СМ ООО «Приоритет», аттестат RA.RU.13НА83',
     'system:migration',
     now(),
     now()),
    ('3784d3bc-f2b0-4938-8205-86c084ec315d',
     'vedal-a-2000-product-sheet',
     'Инкубатор-трансформер VEDAL A-2000',
     'Техническая документация',
     'VEDAL A-2000',
     'vedal-a-2000',
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-a-2000-product-sheet.pdf',
     378808,
     'актуальная редакция',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now()),
    ('9ad6ef40-56fe-4059-9db8-71f749c0bcb0',
     'vedal-r1-product-sheet',
     'Система реанимационная VEDAL R1',
     'Техническая документация',
     'VEDAL R1',
     'vedal-r1',
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-r1-product-sheet.pdf',
     316598,
     'разделено из VEDAL R1, R2',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now()),
    ('98097891-9462-40df-afc5-cc377d5827b4',
     'vedal-r2-product-sheet',
     'Система реанимационная VEDAL R2',
     'Техническая документация',
     'VEDAL R2',
     'vedal-r2',
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-r2-product-sheet.pdf',
     377055,
     'разделено из VEDAL R1, R2',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now()),
    ('a76d1d84-19f9-4f44-bf21-7af2035dcc2f',
     'vedal-t-100-product-sheet',
     'Система терморегулирующая VEDAL T-100',
     'Техническая документация',
     'VEDAL T-100',
     'vedal-t-100',
     'public',
     'pdf',
     true,
     true,
     'ru',
     'vedal-t-100-product-sheet.pdf',
     284504,
     'актуальная редакция',
     'ООО «ВЕДАЛ»',
     'system:migration',
     now(),
     now())
on conflict (slug) do update
set title        = excluded.title,
    doc_group    = excluded.doc_group,
    subject      = excluded.subject,
    product_slug = excluded.product_slug,
    sensitivity  = excluded.sensitivity,
    access       = excluded.access,
    listed       = excluded.listed,
    published    = excluded.published,
    language     = excluded.language,
    storage_key  = excluded.storage_key,
    file_size    = excluded.file_size,
    revision     = excluded.revision,
    source_owner = excluded.source_owner,
    approved_by  = excluded.approved_by,
    updated_at   = now();
